apiVersion: apps/v1
kind: Deployment
metadata:
  name: adservice
spec:
  selector:
    matchLabels:
      app: adservice
  template:
    metadata:
      labels:
        app: adservice
    spec:
      containers:
        - env:
            - name: PORT
              value: XXXXXX
          image: gcr.io/google-samples/microservices-demo/adservice:v0.3.0
          livenessProbe:
            exec:
              command:
                - /bin/grpc_health_probe
                - '-addr=:9555'
            initialDelaySeconds: 20
            periodSeconds: 15
          name: server
          ports:
            - containerPort: 9555
          readinessProbe:
            exec:
              command:
                - /bin/grpc_health_probe
                - '-addr=:9555'
            initialDelaySeconds: 20
            periodSeconds: 15
          resources:
            limits:
              cpu: 300m
              memory: 300Mi
            requests:
              cpu: 200m
              memory: 180Mi
          securityContext:
            runAsNonRoot: 'true'
            allowPrivilegeEscalation: 'false'
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
