apiVersion: apps/v3
kind: DaemonSet
metadata:
  annotations:
    deprecated.daemonset.template.generation: '1'
    meta.helm.sh/release-name: tetragon
    meta.helm.sh/release-namespace: kube-system
  creationTimestamp: '2023-03-04T21:16:07Z'
  generation: 1
  labels:
    app.kubernetes.io/instance: tetragon
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: tetragon
    helm.sh/chart: tetragon-0.8.4
  name: tetragon
  namespace: kube-system
  resourceVersion: '1016842'
  uid: fc0200cd-0b91-4278-b875-0996c4ad76fd
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: tetragon
      app.kubernetes.io/name: tetragon
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: tetragon
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: tetragon
        helm.sh/chart: tetragon-0.8.4
    spec:
      containers:
        - args:
            - /var/run/cilium/tetragon/tetragon.log
          command:
            - hubble-export-stdout
          image: quay.io/cilium/hubble-export-stdout:v1.0.2
          imagePullPolicy: IfNotPresent
          name: export-stdout
          resources: {}
          securityContext: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /var/run/cilium/tetragon
              name: export-logs
        - args:
            - '--config-dir=/etc/tetragon/tetragon.conf.d/'
          command:
            - /usr/bin/tetragon
          env:
            - name: NODE_NAME
              value: XXXXXX
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          image: quay.io/cilium/tetragon:v0.8.4
          imagePullPolicy: IfNotPresent
          livenessProbe:
            exec:
              command:
                - tetra
                - status
                - '--server-address'
                - localhost:54321
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: tetragon
          resources: {}
          securityContext:
            privileged: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /var/lib/tetragon/metadata
              name: metadata-files
            - mountPath: /etc/tetragon/tetragon.conf.d/
              name: tetragon-config
              readOnly: true
            - mountPath: /sys/fs/bpf
              mountPropagation: Bidirectional
              name: bpf-maps
            - mountPath: /var/run/cilium
              name: cilium-run
            - mountPath: /var/run/cilium/tetragon
              name: export-logs
            - mountPath: /procRoot
              name: host-proc
      dnsPolicy: Default
      hostNetwork: true
      initContainers:
        - command:
            - tetragon-operator
          image: quay.io/cilium/tetragon-operator:v0.8.4
          imagePullPolicy: IfNotPresent
          name: tetragon-operator
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: tetragon
      serviceAccountName: tetragon
      terminationGracePeriodSeconds: 1
      tolerations:
        - operator: Exists
      volumes:
        - hostPath:
            path: /var/run/cilium
            type: DirectoryOrCreate
          name: cilium-run
        - hostPath:
            path: /var/run/cilium/tetragon
            type: DirectoryOrCreate
          name: export-logs
        - configMap:
            defaultMode: 420
            name: tetragon-config
          name: tetragon-config
        - hostPath:
            path: /sys/fs/bpf
            type: DirectoryOrCreate
          name: bpf-maps
        - hostPath:
            path: /proc
            type: Directory
          name: host-proc
        - emptyDir: {}
          name: metadata-files
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
